### ISSUE TITLE
[BUG] Embed (signature)

### ISSUE THREAD

**Issue by AlbertUnruh** [NAFTeam/NAFF#305]
**Describe the bug**
Embed.footer doesn't work properly.

**To Reproduce**
```py
from dis_snek import Embed, EmbedFooter
Embed(footer=EmbedFooter())  # will raise an error
```

**Expected behaviour**
The signature expects ``EmbedFooter`` or ``None`` but the code only works with ``dict`` (or ``None``).

**Additional information**
pip freeze: dis_snek==6.0.0

**Comment by LordOfPolls** [comment]
Are you in the support server? If so support threads might be helpful.

Otherwise, we're aware of the issues with embed attributes. In this case use `embed.set_footer`

**Comment by artem30801** [comment]
It looks like it should've been fixed in #167  (or maybe it just aggravated the issue...)

**Comment by AlbertUnruh** [comment]
> It looks like it should've been fixed in #167

the `.from_dict` expects a dictionary and an `EmbedFooter` isn't a `dict` so it isn't fixed there

**Comment by Kigstn** [comment]
#167 fixed parsing embed data from discord (since they send dicts). Looks like this broke as a result of the fix

**Comment by artem30801** [comment]
> the `.from_dict` expects a dictionary and an `EmbedFooter` isn't a `dict` so it isn't fixed there

Now *that* looks like it should've been fixed in 1ce602f5638ffd86fdc9a353881532977f03325e
But it's a recent commit so it's not on master yet IIRC

**Comment by benwoo1110** [comment]
Fix has been included in the latest release. https://github.com/Discord-Snake-Pit/Dis-Snek/releases/tag/7.0.0
